# SPDX-License-Identifier: LicenseRef-CSSL-1.0

steering-rule-primary:
  flowInfos:
    - flowDescription: permit out ip from any to assigned
  precedence: 10
  refTcData:
    - steering-scenario-primary

steering-rule-secondary:
  flowInfos:
    - flowDescription: permit out ip from any to assigned
  precedence: 10
  refTcData:
    - steering-scenario-secondary