# SPDX-License-Identifier: MIT

services:
    omec-gnbsim:
        container_name: omec-gnbsim
        image: oaisoftwarealliance/omec-gnbsim:v2.3-fixes
        privileged: true
        command: bash -c "./gnbsim --cfg gnbsim.yaml && sleep infinity"
        networks:
            public_net:
                ipv4_address: 192.168.70.171
        volumes:
            - ./omec-gnbsim-config.yaml:/gnbsim/bin/gnbsim.yaml
networks:
    public_net:
        name: demo-oai-public-net
        external: True
