
log_level:
  general: debug

register_nf:
  general: yes

http_version: 2
http_request_timeout: 3000


nfs:
  nrf:
    host: 192.168.70.10
    sbi:
      interface_name: oai-core
      port: 8081
    api_version: v1

  amf:
    host: 192.168.70.10
    sbi:
      interface_name: oai-core
      port: 8080
    api_version: v1

smf:
  instance_id: 1
  pid_directory: "/tmp"

  smf_name: "oai-smf"
  relative_capacity: 100

  sbi:
    interface_name: oai-core
    ipv4_address: 192.168.70.10
    port: 8085
    api_version: v1

  n4:
    interface_name: oai-core
    ipv4_address: 192.168.70.10
    port: 8805

  snssai:
    - sst: 1
      sd: "010203"

dnn:
  - dnn: internet
    pdu_session_type: IPV4
    ipv4_subnet: 12.1.1.0/24
    dns:
      ipv4: 8.8.8.8

upf:
  - host: 192.168.70.10
    pfcp:
      interface_name: oai-core
      port: 8805

database:
  type: mysql
  host: 127.0.0.1
  user: test
  password: test
  database_name: oai_db
