#/*
# * SPDX-License-Identifier: MIT
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface Tcpdump/Init Container
#   Valid for Alpine-3.20
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
ARG BASE_IMAGE=docker.io/alpine:3.20
FROM $BASE_IMAGE AS tcpdump-init
ENV TZ=Europe/Paris
LABEL org.openairinterface.image.authors="contact@openairinterface.org"
# We install some debug tools for the moment in addition of mandatory libraries
RUN apk update && \
      apk add --no-cache\
      curl \
      wget \
      psmisc \
      net-tools \
      ethtool \
      tzdata \
      iperf \
      nmap-ncat \
      iproute2 \
      iputils-ping \
      iptables \
      traceroute \
      tcpdump \
      iperf3 \
