# SPDX-License-Identifier: MIT

#---------------------------------------------------------------------
#
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
   name: oai-amf
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: "oai-amf"
spec:
    runPolicy: "Serial"
    source:
        git:
            uri: "https://github.com/openairinterface/oai-cn5g-amf.git"
            ref: "develop"
    strategy:
        dockerStrategy:
            dockerfilePath: "docker/Dockerfile.amf.centos"
    output:
        to:
            kind: "ImageStreamTag"
            name: "oai-amf:develop"
